Add a funtion to forge Android logd entry
flxo/android-logd-logger pull request #13
Opened 2024-03-04 08:58 UTC by DimaWittmann

This PR adds a function that constructs a custom log entry.
I can be used it forge log entries, for example, to forward logs for 3rd party app to lodg

2024-03-05 21:30 UTC, flxo requested changes
Thanks for your contribution. Left some comments.

2024-03-05 21:30 UTC, flxo commented on src/lib.rs
> +//! android_logd_logger::low(buffer_id, pid, thread_id, secs, subsec_nanos, tag, priority, message).unwrap();
Here's a typo. Should be `log`.  Can you please also ensure that rustdoc catches the examples and tries to build them?

2024-03-05 21:30 UTC, flxo commented on src/lib.rs
> +    println!("buffer: {:?}, tag: {:?}, message: {:?}", buffer_id, tag, message);
Please forward the records in the not android case as well. This keeps the equals format.

2024-03-06 11:00 UTC, DimaWittmann commented on src/lib.rs
> +//! android_logd_logger::low(buffer_id, pid, thread_id, secs, subsec_nanos, tag, priority, message).unwrap();
Thank you for suggestion. I checked with the rustdoc

2024-03-06 11:02 UTC, DimaWittmann commented on src/lib.rs
> +    println!("buffer: {:?}, tag: {:?}, message: {:?}", buffer_id, tag, message);
Of course, I was just not sure, I removed this conditional compilation

2024-03-06 22:42 UTC, merged